<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-0KDP1L5" name="com.clc.sel.util.LoginTest" tests="6" failures="1" timestamp="21 Nov 2018 12:16:32 GMT" time="54.857" errors="0">
  <testcase name="verifyUserCredentails" time="8.696" classname="com.clc.sel.util.LoginTest"/>
  <testcase name="verifyUserCredentails" time="10.121" classname="com.clc.sel.util.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [Welcome Admin]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [Welcome Admin]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.clc.sel.util.LoginTest.verifyUserCredentails(LoginTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- verifyUserCredentails -->
  <testcase name="verifyUserCredentails" time="7.679" classname="com.clc.sel.util.LoginTest"/>
  <testcase name="verifyUserCredentails" time="8.406" classname="com.clc.sel.util.LoginTest"/>
  <testcase name="verifyUserCredentails" time="9.392" classname="com.clc.sel.util.LoginTest"/>
  <testcase name="verifyUserCredentails" time="10.563" classname="com.clc.sel.util.LoginTest"/>
</testsuite> <!-- com.clc.sel.util.LoginTest -->
